# Generated by Django 5.2.10 on 2026-02-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extracteddata',
            table='pdf_processor_extracteddata',
        ),
        migrations.AlterModelTable(
            name='pdfdocument',
            table='pdf_processor_pdfdocument',
        ),
    ]
