# Generated by Django 5.2.10 on 2026-02-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0002_alter_extracteddata_table_alter_pdfdocument_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pdfdocument',
            table='pdf_processor_pdfdocument',
        ),
        migrations.AlterModelTable(
            name='extracteddata',
            table='pdf_processor_extracteddata',
        ),
    ]
