# Generated by Django 5.2.10 on 2026-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0003_rename_tables_to_follow_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL the PDF was scraped/downloaded from', null=True),
        ),
    ]
