# Generated by Django 5.2.10 on 2026-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0004_pdfdocument_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('structured_companies', 'Structured Companies')], max_length=20),
        ),
    ]
