# Generated by Django 5.2.10 on 2026-02-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0005_alter_extracteddata_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='scraped_url',
            field=models.URLField(blank=True, help_text='URL the PDF was scraped from', null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='data_type',
            field=models.CharField(choices=[('structured_companies', 'Structured Companies')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL the PDF was downloaded from', null=True),
        ),
    ]
