# Generated by Django 5.2.10 on 2026-03-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0006_pdfdocument_scraped_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'ordering': ['pdf_document', 'page_number', 'created_at'], 'verbose_name_plural': 'Extracted Data'},
        ),
    ]
