# Generated by Django 4.2.19 on 2025-03-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companylocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companies.CompanyLocation', to='locations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='companyadmin',
            unique_together={('company', 'user')},
        ),
    ]
