# Generated by Django 4.2.19 on 2025-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reviews_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='reviews_rating',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
