# Generated by Django 5.2.10 on 2026-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_id',
            field=models.CharField(blank=True, help_text='Legal identification number (e.g., Croatian OIB)', max_length=50, null=True),
        ),
    ]
