# Generated by Django 5.2.10 on 2026-02-10 20:04

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_legal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
