# Generated by Django 5.2.10 on 2026-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_display_name_alter_company_id_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
