# Generated by Django 5.2.10 on 2026-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_blacklisted_at_company_last_blacklisted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Agency', 'Agency'), ('Accommodation', 'Accommodation'), ('Gastronomy', 'Gastronomy'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=50),
        ),
    ]
