# Generated by Django 5.2.10 on 2026-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_is_certified_alter_company_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Agency', 'Agency'), ('Employment Agency', 'Employment Agency'), ('Tourism Agency', 'Tourism Agency'), ('Accommodation', 'Accommodation'), ('Gastronomy', 'Gastronomy'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
