# Generated by Django 5.2.10 on 2026-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_category_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Agency', 'Agency'), ('Employment Agency', 'Employment Agency'), ('Tourism Agency', 'Tourism Agency'), ('Accommodation', 'Accommodation'), ('Gastronomy', 'Gastronomy'), ('Entertainment', 'Entertainment'), ('Construction', 'Construction'), ('Non-profit Organization', 'Non Profit Organization'), ('Other', 'Other')], max_length=50),
        ),
    ]
