# Generated by Django 5.2.10 on 2026-03-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_created_via'),
        ('locations', '0012_alter_country_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_id_type',
            field=models.CharField(blank=True, help_text='Type of legal identification (e.g., OIB, EIN)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_id',
            field=models.CharField(blank=True, help_text='Legal identification number', max_length=50, null=True),
        ),
    ]
