# Generated by Django 5.2.10 on 2026-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_company_address_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating_summary',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
