# Generated by Django 5.2.10 on 2026-03-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_rating_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='raw_address',
        ),
    ]
