# Generated by Django 5.2.10 on 2026-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_rename_address_company_raw_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='related_companies',
            field=models.ManyToManyField(blank=True, to='companies.company'),
        ),
    ]
