# Generated by Django 5.2.10 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_related_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_location',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
