# Generated by Django 4.2.19 on 2025-03-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('hiring_type', models.CharField(choices=[('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Employee', 'Employee'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], default='Employee', max_length=100)),
                ('hours', models.CharField(choices=[('Full-time', 'Full Time'), ('Part-time', 'Part Time'), ('Flexible', 'Flexible'), ('Other', 'Other')], default='Full-time', max_length=100)),
                ('duration', models.CharField(choices=[('Casual', 'Casual'), ('Seasonal', 'Seasonal'), ('Long-term', 'Long Term'), ('Other', 'Other')], default='Seasonal', max_length=100)),
                ('place', models.CharField(choices=[('On-site', 'On Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On-site', max_length=100)),
                ('has_sponsorship', models.BooleanField(default=False)),
                ('has_accommodation', models.BooleanField(default=False)),
                ('has_meal', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
