# Generated by Django 5.2.10 on 2026-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], default='Regular', max_length=100),
        ),
    ]
