# Generated by Django 5.2.10 on 2026-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_hiring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_relocation',
            field=models.BooleanField(default=False),
        ),
    ]
