# Generated by Django 4.0 on 2024-03-28 16:41

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_name', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('legal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Accommodation', 'Accommodation'), ('Gastronomy', 'Gastronomy'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=50)),
                ('picture', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('hiring_type', models.CharField(choices=[('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Employee', 'Employee'), ('Other', 'Other')], default='Employee', max_length=100)),
                ('hours', models.CharField(choices=[('Full-time', 'Full Time'), ('Part-time', 'Part Time')], default='Full-time', max_length=100)),
                ('duration', models.CharField(choices=[('Casual', 'Casual'), ('Seasonal', 'Seasonal'), ('Long-term', 'Long Term'), ('Other', 'Other')], default='Seasonal', max_length=100)),
                ('place', models.CharField(choices=[('On-site', 'On Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On-site', max_length=100)),
                ('has_sponsorship', models.BooleanField(default=False)),
                ('has_accommodation', models.BooleanField(default=False)),
                ('has_meal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('salary_range', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur')], default='USD', max_length=50)),
                ('salary_frequency', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], default='Monthly', max_length=50)),
                ('comment', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='expatsapp.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
