# Generated by Django 4.0 on 2024-03-08 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('expatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('subregion', models.CharField(choices=[('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('Caribbean', 'Caribbean'), ('Central & South Asia', 'Central South Asia'), ('Northeastern Asia', 'Northeastern Asia'), ('Southeastern Asia', 'Southeastern Asia'), ('Australia and Oceania', 'Australia Oceania'), ('Northern Europe', 'Northern Europe'), ('Southern Europe', 'Southern Europe'), ('Eastern Europe', 'Eastern Europe'), ('Western Europe', 'Western Europe'), ('Middle East', 'Middle East'), ('Northern Africa', 'Northern Africa'), ('Southern Africa', 'Southern Africa')], max_length=50)),
                ('business_region', models.CharField(choices=[('Americas', 'Amer'), ('Asia & Pacific', 'Apac'), ('Europe Middle East/Africa', 'Emea')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(choices=[('Business', 'Business'), ('Shipping', 'Shipping'), ('Billing', 'Billing')], default='Business', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_1', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_2', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_3', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_4', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_5', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='expatsapp.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        # Customized migration: Removed and added location field instead alter it
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expatsapp.location'),
        ),
    ]
