# Generated by Django 4.0 on 2024-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('expatsapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
    ]
