# Generated by Django 4.0 on 2024-03-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0002_country_location_alter_company_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
