# Generated by Django 4.0 on 2024-03-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0003_alter_country_options_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='expatsapp.company'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Business', 'Business'), ('Contact', 'Contact'), ('Home', 'Home'), ('Shipping', 'Shipping')], default='Business', max_length=100),
        ),
    ]
