# Generated by Django 4.0 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0003_alter_company_locations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('company', 'reviewer'), name='unique_reviewer_per_company'),
        ),
    ]
