# Generated by Django 4.0 on 2024-03-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0004_remove_company_location_location_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='salary_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='expatsapp.company'),
        ),
    ]
