# Generated by Django 4.0 on 2024-03-09 11:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0005_review_salary_currency_review_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
