# Generated by Django 4.0 on 2024-03-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_display_name'),
        ('expatsapp', '0007_remove_company_name_company_id_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='worker',
            new_name='reviewer',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('hiring_type', models.CharField(choices=[('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Employee', 'Employee'), ('Other', 'Other')], default='Employee', max_length=100)),
                ('hours', models.CharField(choices=[('Full-time', 'Full Time'), ('Part-time', 'Part Time')], default='Full-time', max_length=100)),
                ('duration', models.CharField(choices=[('Casual', 'Casual'), ('Seasonal', 'Seasonal'), ('Long-term', 'Long Term'), ('Other', 'Other')], default='Seasonal', max_length=100)),
                ('place', models.CharField(choices=[('On-site', 'On Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On-site', max_length=100)),
                ('has_sponsorship', models.BooleanField(default=False)),
                ('has_accommodation', models.BooleanField(default=False)),
                ('has_meal', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='expatsapp.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
