# Generated by Django 4.0 on 2024-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0008_rename_worker_review_reviewer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='salary_frequency',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='salary_currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur')], default='USD', max_length=50),
        ),
    ]
