# Generated by Django 4.0 on 2024-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatsapp', '0009_review_salary_frequency_alter_review_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
