# Generated by Django 4.0 on 2024-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Croatian'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=10),
        ),
    ]
