# Generated by Django 5.2.10 on 2026-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_name_alter_post_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Croatian'), ('de', 'German'), ('es', 'Spanish')], max_length=10),
        ),
    ]
