# Generated by Django 4.0 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_name_alter_post_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Croatian'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=10),
        ),
    ]
