# Generated by Django 4.2.19 on 2025-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Croatian'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=10),
        ),
    ]
