# Generated by Django 4.2.19 on 2025-03-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_branch_options'),
        ('locations', '0002_alter_location_level_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
        migrations.AddField(
            model_name='address',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='location',
            name='level_type',
            field=models.CharField(choices=[('CITY', 'City'), ('COUNTY', 'County'), ('DEPARTMENT', 'Department'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality'), ('PROVINCE', 'Province'), ('REGION', 'Region'), ('STATE', 'State'), ('TOWN', 'Town'), ('VILLAGE', 'Village')], default='CITY', max_length=50),
        ),
    ]
