# Generated by Django 4.2.19 on 2025-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_address_company_address_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='level_type',
            field=models.CharField(choices=[('CITY', 'City'), ('COUNTY', 'County'), ('DEPARTMENT', 'Department'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality'), ('PROVINCE', 'Province'), ('REGION', 'Region'), ('STATE', 'State'), ('TOWN', 'Town'), ('VILLAGE', 'Village')], default='CITY', max_length=50),
        ),
    ]
