# Generated by Django 4.2.19 on 2026-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_address_branch_alter_location_level_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='location',
            name='level_type',
            field=models.CharField(choices=[('CITY', 'City'), ('COUNTY', 'County'), ('DEPARTMENT', 'Department'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality'), ('PROVINCE', 'Province'), ('REGION', 'Region'), ('STATE', 'State'), ('TOWN', 'Town'), ('VILLAGE', 'Village')], default='CITY', max_length=50),
        ),
    ]
