# Generated by Django 5.2.10 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_remove_address_user_alter_location_level_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
