# Generated by Django 4.2.19 on 2025-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_level_type'),
        ('companies', '0003_alter_company_reviews_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyLocation',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='company',
            name='picture',
        ),
    ]
