# Generated by Django 4.2.19 on 2025-03-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_location_level_type'),
        ('companies', '0005_alter_branch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='locations',
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.location'),
        ),
    ]
