# Generated by Django 4.2.19 on 2025-04-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_address_branch_alter_location_level_type'),
        ('companies', '0006_remove_company_locations_alter_branch_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.address'),
        ),
    ]
