# Generated by Django 4.0 on 2024-03-28 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('subregion', models.CharField(choices=[('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('Caribbean', 'Caribbean'), ('Central & South Asia', 'Central South Asia'), ('Northeastern Asia', 'Northeastern Asia'), ('Southeastern Asia', 'Southeastern Asia'), ('Australia and Oceania', 'Australia Oceania'), ('Northern Europe', 'Northern Europe'), ('Southern Europe', 'Southern Europe'), ('Eastern Europe', 'Eastern Europe'), ('Western Europe', 'Western Europe'), ('Middle East', 'Middle East'), ('Northern Africa', 'Northern Africa'), ('Southern Africa', 'Southern Africa')], max_length=50)),
                ('business_region', models.CharField(choices=[('Americas', 'Amer'), ('Asia & Pacific', 'Apac'), ('Europe Middle East/Africa', 'Emea')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_1', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_2', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_3', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_4', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_5', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('Billing', 'Billing'), ('Business', 'Business'), ('Contact', 'Contact'), ('Home', 'Home'), ('Shipping', 'Shipping')], default='Business', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='expatsapp.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
