# Generated by Django 4.2.19 on 2025-04-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_locations_alter_branch_company_and_more'),
        ('locations', '0008_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='level_type',
            field=models.CharField(choices=[('CITY', 'City'), ('COUNTY', 'County'), ('DEPARTMENT', 'Department'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality'), ('PROVINCE', 'Province'), ('REGION', 'Region'), ('STATE', 'State'), ('TOWN', 'Town'), ('VILLAGE', 'Village')], default='CITY', max_length=50),
        ),
    ]
