# Generated by Django 4.2.19 on 2025-04-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_address_branch_alter_address_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='branch',
        ),
        migrations.AlterField(
            model_name='location',
            name='level_type',
            field=models.CharField(choices=[('CITY', 'City'), ('COUNTY', 'County'), ('DEPARTMENT', 'Department'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality'), ('PROVINCE', 'Province'), ('REGION', 'Region'), ('STATE', 'State'), ('TOWN', 'Town'), ('VILLAGE', 'Village')], default='CITY', max_length=50),
        ),
    ]
