# Generated by Django 5.2.10 on 2026-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
