# Generated by Django 5.2.10 on 2026-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_reviewer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
